
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zookeeper_demo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    container_name: kafka_demo
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092

  mysql:
    image: mysql:8.0
    container_name: mysql_demo
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: debezium
      MYSQL_PASSWORD: Dbz12345!
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    command:
      --server-id=184054
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --transaction-isolation=READ-COMMITTED
      --binlog-do-db=testdb

  connect:
    image: quay.io/debezium/connect:1.9
    container_name: debezium_demo
    platform: linux/amd64
    depends_on:
      - kafka
      - mysql
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop_demo
    platform: linux/amd64
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms32M -Xmx64M
